### ISSUE TITLE
[CM14]Buttons设置里的last app无效

### ISSUE THREAD

**Issue by hujy23** [MI3TD/android_device_xiaomi_pisces#16]
我试着把长按home键以及双击home键设为last app都没有反应。

   另外我的手机在CM13的时候就是recent键失效，无论设置里面怎么改，他都是：短按-菜单，长按-无反应。这个好像是比较老的安卓版本里面，菜单键作作用。这个我感觉是我自己手机的问题，好像没听过别人有这个问题……

   话说这里怎么没有汉化，虽然不影响~

**Comment by VisoTC** [comment]
经过测试，在版本CM14-20161112下无法复现问题，建议更新到最新版本
另外，建议以后其他版本问题单独开一个新的issue

**Comment by hujy23** [comment]
@szlytlyt 嗯嗯，的确last app后面的版本可用了，thx
