### ISSUE TITLE
[CM14] 1027 硬重启频繁

### ISSUE THREAD

**Issue by hujy23** [MI3TD/android_device_xiaomi_pisces#27]
感觉基本上是由wifi或者流量开关触发的，有时候关闭或打开流量开关或wifi开关就重启了，有时候下拉通知栏就重启。有时候拍照卡住也重启。
[last_kmsg >>](http://pan.baidu.com/s/1eRMxsVS)

**Comment by xuefer** [comment]
这个跟基带通讯有问题, 请重新刷一下基带试试, 官方卡刷包提取 blob 改名为 blob.img 用 TWRP 刷到 staging 分区 (或者 fastboot flash staging blob.img)

**Comment by hujy23** [comment]
@xuefer 试了下的确好了，目前两个小时没重启，谢谢:)
