### ISSUE TITLE
请问是否支持usb调试？AndroidStudio不识别手机

### ISSUE THREAD

**Issue by TellH** [MI3TD/android_device_xiaomi_pisces#34]
作者您好，我是Android App开发者。刷了该rom后，AS识别不到设备，是不支持usb调试吗？

**Comment by xuefer** [comment]
开发者选项里打开 adb 调试, 可以的. 能不能支持得去设置, 莫非你不会设置

**Comment by TellH** [comment]
设置里找不到开发者选项

**Comment by xuefer** [comment]
这种问题就不要在这里问了. 上网问任何人任何设备的用户都可以. 再见

**Comment by TellH** [comment]
非常非常抱歉，打扰了
