### ISSUE TITLE
[LineageOS 14.1] 频繁硬重启

### ISSUE THREAD

**Issue by prinsss** [MI3TD/android_device_xiaomi_pisces#35]
刷入的是 20170611 的版本，经常性卡顿，表现为「本来挺流畅的，突然变卡一下，几秒钟后恢复」，QQ、Chrome、视频播放等各种应用中均有出现。严重情况下持续卡顿几秒后直接黑屏白米硬重启，有时候在自动重启过程中又会再次重启。

进入 Recovery 中抓取的
`last_kmsg` 在这里：https://www.dropbox.com/s/sl2gt8msk5n57ig/last_kmsg?dl=0

还有 [另外一个 `last_kmsg`](https://www.dropbox.com/s/mi70oois5b2ixhf/last_kmsg2?dl=0)，是上述「重启过程中再次黑屏重启」后抓取的内核日志。

**Comment by hujy23** [comment]
完全一样的表现，“本来挺流畅的，突然变卡一下，几秒钟后恢复”这个描述的非常贴切。硬重启是发生在原本连着WiFi，但离开WiFi后，切换到流量的时候，gg，信号图标空了，硬重启。

**Comment by xuefer** [comment]
卡的问题已知/另外的解决
重启问题, 看日志是基带问题. 你自己解决基带或者禁用基带可解决你的问题

**Comment by hujy23** [comment]
@xuefer 官方线刷包的基带刷进去也没用，还是一样_(:з」∠)_禁用基带就不能打电话了吧

**Comment by xuefer** [comment]
基带硬件不稳定刷基带也没用, 刷基带只是因为基带固件丢了. 也就只能试试刷别的版本的rom 如果没问题那就是系统兼容问题了

**Comment by hujy23** [comment]
@xuefer 隐约觉得不是硬件问题，因为CM13和MIUI没问题，这次刷14.1之前用了4个月CM13，没基带问题_(:з」∠)_

**Comment by prinsss** [comment]
我也认为不是基带硬件问题，因为同样的机器安装 LineageOS 13 和基于同样底包的 Flyme6 都不会出现类似情况。
