### ISSUE TITLE
cm-12.1 20170303 自带时钟和电子邮件停止运作

### ISSUE THREAD

**Issue by zhou0** [MI3TD/android_device_xiaomi_pisces#38]
安装之后出现反复出现“很抱歉，时钟已停止运作。 确定”和“很抱歉，电子邮件已停止运作。 确定“的错误消息。

暂时解决方法是将时钟和电子邮件app停用。

**Comment by xuefer** [comment]
清空单个应用的数据试试

**Comment by zhou0** [comment]
依照上述方法成功解决问题·！
