### ISSUE TITLE
[CM14] 希望屏幕方向锁定时，通知栏不要显示那个横向/纵向图标

### ISSUE THREAD

**Issue by hujy23** [MI3TD/android_device_xiaomi_pisces#8]

**Comment by xuefer** [comment]
通知栏没有显示, 不知道你说的显示了什么

**Comment by hujy23** [comment]
![](http://ww4.sinaimg.cn/large/005JFI4ogw1f889t04juej30u01hc1kx.jpg)
右上角那里不是有一个竖着放的手机图标吗

**Comment by xuefer** [comment]
这个是cm的东西, 我手头上已经没有这个了, 在设置里 最底部 "系统UI调节"什么的, System UI Tuner, 25号的版本好多设置, 我的26号就没了

**Comment by hujy23** [comment]
哦哦，这个其实也没啥影响，处女座……那个的翻译是**系统界面调节工具**
